### ISSUE TITLE
HP OMEN 15 (2018) ce004la

### ISSUE THREAD

**Issue by Pablo1107** [T-vK/gpu-passthrough.com#3]
Hi, sorry I'm not posting a compatible devices, but want to let others know this computer dosn't give users the option to use the integrated graphics, it's completely MUXless and the outputs and the display are hooked directly to the dGPU (reducing the battery life considerably).

``` JSON
{
    "name": "HP OMEN 15 (2018) ce004la",
    "cpu": "Intel Core i7-7700HQ",
    "gpus": [
        {
            "name": "GTX 1060 Mobile with Max-Q design (6GB)",
            "type": "dGPU",
            "passthrough-guests": {}
        }
    ],
    "checklist": {
        "linux-compatible": "Yes, no issues",
        "at-least-two-usable-gpus": "No",
        "cpu-supports-iommu": "Yes",
        "chipset-supports-iommu": "Yes",
        "uefi-supports-iommu": "Yes",
        "igpu-usable": "No",
        "muxed": "No"
    },
    "tested-by": [
        { "name": "pablo1107", "url": "https://github.com/pablo1107" }
    ],
    "notes": "Completaly MUXless, output hooked to dGPU"
}
```

**Comment by T-vK** [comment]
Oh, you mean the iGPU is completely disabled? Have you checked the BIOS/UEFI for an option to enable it?

**Comment by Pablo1107** [comment]
Yes I checked, but it's interesting that your script tells otherwise.

```
OK] VT-X / AMD-V virtualization is enabled in the UEFI.
[OK] VT-D / IOMMU is enabled in the UEFI.
[OK] The IOMMU kernel parameters are set.
[Success] GPU with ID '01:00.0' could be passed through to a virtual machine!
[Success] There are 1 GPU(s) in this system that could be passed through to a VM!

Is Compatible?  Name                                   IOMMU_GROUP  PCI Address
Yes             GP106BM [GeForce GTX 1060 Mobile 6GB]  1            pci@0000:01:00.0

[Warning] Only 1 GPU found! (Counting all GPUs, not just dedicated ones.) This would make GPU pass-thruogh difficult (not impossible) because your host machine would be left without a GPU!
[Info] Device name: OMEN by HP Laptop 15-ce0xx
[Info] BIOS version: F.17
[OK] This system is probably MUXed. (The connection between the GPU(s) and the [internal display]/[display outputs] is multiplexed.)
[OK] Logs have been created in /home/pablo1107/GPU-pass-through-compatibility-check/logs/OMEN by HP Laptop 15-ce0xx/F.17
TODO: create a VM and pass a GPU through to it
```

**Comment by Pablo1107** [comment]
I don't know what part of the script tells whatever the bios have switchable graphics or not, maybe I can give you one of the logs?

**Comment by T-vK** [comment]
Since the script only detects the Nvidia dGPU and you don't have an option to enable the iGPU in the BIOS/UEFI, it would be very difficult to make GPU passthrough work on that machine and probably not worth the effort. 
I do have a theory that the muxing and the disabling of the iGPU is software-controlled (fromt he BIOS/UEFI) on some notebooks. At least I found some hidden options suggesting that, while modding the UEFI of my current notebook. But even if you managed to get that to work, you'd end up with error 43 if you tried to pass a 10xx Nvidia GPU through to a Windows VM.
